[2023-04-13T12:53:23.243+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_connection.create_table manual__2023-04-13T12:53:12.944081+00:00 [queued]>
[2023-04-13T12:53:23.279+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_connection.create_table manual__2023-04-13T12:53:12.944081+00:00 [queued]>
[2023-04-13T12:53:23.281+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:53:23.283+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-13T12:53:23.286+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:53:23.315+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-13 12:53:12.944081+00:00
[2023-04-13T12:53:23.332+0000] {standard_task_runner.py:55} INFO - Started process 1925 to run task
[2023-04-13T12:53:23.346+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_connection', 'create_table', 'manual__2023-04-13T12:53:12.944081+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_create_table.py', '--cfg-path', '/tmp/tmpgxz1wpv4']
[2023-04-13T12:53:23.351+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask create_table
[2023-04-13T12:53:23.546+0000] {task_command.py:389} INFO - Running <TaskInstance: test_connection.create_table manual__2023-04-13T12:53:12.944081+00:00 [running]> on host b030a83adc1d
[2023-04-13T12:53:23.749+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlngueko
AIRFLOW_CTX_DAG_ID=test_connection
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T12:53:12.944081+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T12:53:12.944081+00:00
[2023-04-13T12:53:23.755+0000] {sql.py:254} INFO - Executing:  create table if not exists test_tab (
        id integer,
        name character,
        timestamp timestamp,
        primary key id)
        
[2023-04-13T12:53:23.789+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-04-13T12:53:24.604+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-04-13T12:53:24.716+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  password authentication failed for user "***"

[2023-04-13T12:53:24.748+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=test_connection, task_id=create_table, execution_date=20230413T125312, start_date=20230413T125323, end_date=20230413T125324
[2023-04-13T12:53:24.795+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task create_table (connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  password authentication failed for user "***"
; 1925)
[2023-04-13T12:53:24.836+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T12:53:24.875+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
