[2023-04-13T12:58:28.012+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_connection.create_table scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-13T12:58:28.044+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_connection.create_table scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-13T12:58:28.047+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:58:28.049+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 6
[2023-04-13T12:58:28.051+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:58:28.100+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-11 00:00:00+00:00
[2023-04-13T12:58:28.121+0000] {standard_task_runner.py:55} INFO - Started process 2046 to run task
[2023-04-13T12:58:28.132+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_connection', 'create_table', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_create_table.py', '--cfg-path', '/tmp/tmpcvp6sjvk']
[2023-04-13T12:58:28.138+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask create_table
[2023-04-13T12:58:28.393+0000] {task_command.py:389} INFO - Running <TaskInstance: test_connection.create_table scheduled__2023-04-11T00:00:00+00:00 [running]> on host b030a83adc1d
[2023-04-13T12:58:28.661+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlngueko
AIRFLOW_CTX_DAG_ID=test_connection
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-13T12:58:28.666+0000] {sql.py:254} INFO - Executing:  create table if not exists test_tab (
        id integer,
        name character,
        timestamp timestamp,
        primary key id)
        
[2023-04-13T12:58:28.695+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-04-13T12:58:29.337+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-04-13T12:58:29.342+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-04-13T12:58:29.361+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=test_connection, task_id=create_table, execution_date=20230411T000000, start_date=20230413T125828, end_date=20230413T125829
[2023-04-13T12:58:29.391+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task create_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 2046)
[2023-04-13T12:58:29.419+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T12:58:29.457+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
